@startuml

skinparam style strictuml

title RDCU pour redémarrerJeu

participant ":JeuDeDes" as jeux
participant "joueurs: Map<String, Joueur>" as joueurs

-> jeux : redemarrerJeu()
note right of jeux : selon Contrôleur\n (JeuDeDés est\n l'objet racine)

jeux -> joueurs : clear()
note right of joueurs : selon Expert


@enduml